import { refillCommand, enderPearlCommand, inflatableJerriesCommand } from "./commands/RefillCommand"
import { rotate } from "./commands/Rotate"
import { sound } from "./commands/SoundCommand"
import { valleyCommand } from "./commands/ValleyCommand"
import { pb } from "./commands/PbCommand"
import { leapOrder } from "./commands/LeapOrder"

import "./features/AtLocationMessages"
import "./features/AutoOpenPotionBag"
import "./features/AutoRefill"
import "./features/BloodCampHelper"
import "./features/BloodRushSplits"
import "./features/CompactHoppityMessages"
import "./features/CrystalPlaceTimer"
import "./features/CrystalSpawnTimer"
import "./features/DistanceToLedge"
import "./features/DragonSpawnTimer"
import "./features/DungeonWarpCooldown"
import "./features/DupeClassChecker"
import "./features/ExplosiveShot"
import "./features/GoldorTickTimer"
import "./features/HidePlayersAfterLeap"
import "./features/InvincibilityMessages"
import "./features/ItemHighlight"
import "./features/LeapNotification"
import "./features/LimboCommand"
import "./features/MelodyWarning"
import "./features/P3StartTimer"
import "./features/PadTickTimer"
import "./features/PestUtils"
import "./features/PictureOnScreen"
import "./features/PillarExplode"
import "./features/PredevTimer"
import "./features/Pre4Notifier"
import "./features/RagDisplay"
import "./features/RelicSpawnTimer"
import "./features/RelicTimer"
import "./features/RelicUtils"
import "./features/RunSplits"
import "./features/SlayerMiniAlert"
import "./features/Stopwatch"
import "./features/TerminalTimestamps"
import "./features/WitherBloodKeys"

import "./util/FirstInstall"